# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import gondola_grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('gondola_grid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gondola',
        ),
        migrations.DeleteModel(
            name='GondolaRow2R',
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='image_2',
            field=models.ImageField(default='', upload_to='gondole_img', validators=[gondola_grid.models.validate_gondola]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='gondole_img', validators=[gondola_grid.models.validate_gondola]),
        ),
        migrations.AlterField(
            model_name='gondolerow',
            name='image_1',
            field=models.ImageField(upload_to='gondole_img', validators=[gondola_grid.models.validate_gondola]),
        ),
    ]
