# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import gondola_grid.models


class Migration(migrations.Migration):

    dependencies = [
        ('gondola_grid', '0002_auto_20170224_1404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GondolaRowCCR',
        ),
        migrations.DeleteModel(
            name='GondolaRowCRC',
        ),
        migrations.DeleteModel(
            name='GondolaRowRCC',
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='label',
            field=models.CharField(default='Gondole row', max_length=250),
        ),
        migrations.AlterField(
            model_name='gondolerow',
            name='image_1',
            field=models.ImageField(upload_to='', validators=[gondola_grid.models.validate_gondola]),
        ),
        migrations.AlterField(
            model_name='gondolerow',
            name='image_2',
            field=models.ImageField(upload_to='', validators=[gondola_grid.models.validate_gondola]),
        ),
        migrations.AlterField(
            model_name='gondolerow',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[gondola_grid.models.validate_gondola]),
        ),
    ]
