# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gondola_grid', '0003_auto_20170224_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gondolerow',
            options={'ordering': ['active', 'modified', 'created'], 'verbose_name': 'Gondola row', 'verbose_name_plural': 'Gondola rows'},
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='gondolerow',
            name='position',
            field=models.SmallIntegerField(default=1, max_length=2),
        ),
    ]
